version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./data/uploads:/app/data/uploads
      - ./app.db:/app/app.db
    environment:
      - PYTHONUNBUFFERED=1
      - APP_CONFIG_DIR=config/container

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      - backend
